version: "3.8"

services:

  backend:
    build: ./backend
    ports:
      - "5002:5000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always