name: CI/CD Pipeline - Portfolio9

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Frontend image
        run: docker build -t protfolio9-frontend:latest ./frontend

      - name: Build Backend image
        run: docker build -t protfolio9-backend:latest ./backend

      - name: Run Backend tests
        run: |
          cd backend
          npm install
          npm test --if-present || true

      - name: Verify Kubernetes manifests
        run: |
          echo "Verifying Kubernetes manifests..."
          cat k8s/secret.yaml
          cat k8s/backend-deployment.yaml
          cat k8s/frontend-deployment.yaml
          echo "All manifests verified!"

  terraform:
    runs-on: ubuntu-latest
    needs: build-and-test
    outputs:
      ec2_ip_1: ${{ steps.tf_output.outputs.ec2_ip_1 }}
      ec2_ip_2: ${{ steps.tf_output.outputs.ec2_ip_2 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init
        run: cd terraform && terraform init

      - name: Terraform Plan
        run: cd terraform && terraform plan

      - name: Get Terraform Outputs
        id: tf_output
        run: |
          cd terraform
          EC2_IP_1=$(terraform output -json instance_public_ips | jq -r '.[0]')
          EC2_IP_2=$(terraform output -json instance_public_ips | jq -r '.[1]')
          echo "ec2_ip_1=$EC2_IP_1" >> $GITHUB_OUTPUT
          echo "ec2_ip_2=$EC2_IP_2" >> $GITHUB_OUTPUT
          echo "IP1: $EC2_IP_1"
          echo "IP2: $EC2_IP_2"

  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: sudo apt install -y ansible

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ma-cle-aws.pem
          chmod 600 ~/.ssh/ma-cle-aws.pem

      

      - name: Run Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory.ini deploy.yml

      - name: Deployment Success
        run: |
          echo "✅ Déploiement terminé avec succès!"
          echo "🌐 Application disponible via ALB"
